name: Generate binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Binary
      run: pyinstaller --onefile --name verify_dump src/verify_dump.py
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: verify_dump
        path: dist/verify_dump
